apiVersion: v1
kind: PersistentVolume
metadata:
  name: standard
spec:
   capacity:
     storage: 5Gi
   volumeMode: Filesystem
   accessModes:
     - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   nfs:
     path: /tmp
     server: 172.17.0.2
